// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4f-N-t7VIfSoqlppzl3xdL0LX9iafZ6E',
    appId: '1:580370011894:web:c02fb798ee1c1be83abed7',
    messagingSenderId: '580370011894',
    projectId: 'notification12-871f3',
    authDomain: 'notification12-871f3.firebaseapp.com',
    storageBucket: 'notification12-871f3.firebasestorage.app',
    measurementId: 'G-P90EXVKHG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsIp4ft6YFv98e9_MgNVz8E9TdQns9w98',
    appId: '1:580370011894:android:8b3de404a4febdca3abed7',
    messagingSenderId: '580370011894',
    projectId: 'notification12-871f3',
    storageBucket: 'notification12-871f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeFQTCYMbUVzfkma7w1VkzIYhB81MucU',
    appId: '1:580370011894:ios:92b8ad4bdc9007003abed7',
    messagingSenderId: '580370011894',
    projectId: 'notification12-871f3',
    storageBucket: 'notification12-871f3.firebasestorage.app',
    iosBundleId: 'com.example.notificationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEeFQTCYMbUVzfkma7w1VkzIYhB81MucU',
    appId: '1:580370011894:ios:92b8ad4bdc9007003abed7',
    messagingSenderId: '580370011894',
    projectId: 'notification12-871f3',
    storageBucket: 'notification12-871f3.firebasestorage.app',
    iosBundleId: 'com.example.notificationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4f-N-t7VIfSoqlppzl3xdL0LX9iafZ6E',
    appId: '1:580370011894:web:f065ef10e8dfb5863abed7',
    messagingSenderId: '580370011894',
    projectId: 'notification12-871f3',
    authDomain: 'notification12-871f3.firebaseapp.com',
    storageBucket: 'notification12-871f3.firebasestorage.app',
    measurementId: 'G-VPC6PVPKXZ',
  );
}
